version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: seraaj
      POSTGRES_USER: seraaj
      POSTGRES_PASSWORD: seraaj_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    
  bff:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: python -m bff.main
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://seraaj:seraaj_dev@postgres/seraaj
      REDIS_URL: redis://redis:6379

volumes:
  postgres_data: