type: object
title: SubmitApplicationCommand
description: Command to submit a volunteer application
required:
  - volunteerId
  - opportunityId
properties:
  volunteerId:
    type: string
    format: uuid
    description: ID of the volunteer submitting the application
  opportunityId:
    type: string
    format: uuid
    description: ID of the opportunity being applied to
  coverLetter:
    type: string
    maxLength: 1000
    description: Optional cover letter from volunteer